### ISSUE TITLE
deploy

### ISSUE THREAD

**Issue by EliasSalom** [Fullstack-Alfanar/api-movies#2]
please check your deploy environment, it's not working, fix it and update me

**Comment by EliasSalom** [comment]
why you are using GitHub pages to deploy your project, please work as we learn in the class to deploy on Heroku,
Github Pages doesn't create for this type of use

**Please check your deployment environment**

**Comment by ameer1004** [comment]
Hi 
I know but I wanted to check if its work in github pages. 
I will remove github pages environment in my project

**Comment by ameer1004** [comment]
hi elias 
I pushed my project to another file to new repo and my deploy in heroku will work now. 
I will open new pull request to the new project repo.

**Comment by ameer1004** [comment]
hi elias 
I pushed my project to another file to new repo and my deploy in heroku will work now. 
I will open new pull request to the new project repo.
